export const BEAD_RETRY_BUDGET_EXHAUSTED = 'BEAD_RETRY_BUDGET_EXHAUSTED' as const
export const OPENCODE_OUTPUT_TRUNCATED = 'OPENCODE_OUTPUT_TRUNCATED' as const
export const OPENCODE_PROVIDER_AUTH_FAILED = 'OPENCODE_PROVIDER_AUTH_FAILED' as const
export const OPENCODE_PROVIDER_ERROR = 'OPENCODE_PROVIDER_ERROR' as const
